spring:
  application:
    name: blps1

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    admin:
      properties:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
    bootstrapServers:
      - localhost:9092
    topics:
      - name: "generate-report"
        partitions: 1
        replication-factor: 1

security:
  token: ${SECURITY_KEY}
  expiration-time-ms: 172800000

scheduler:
  landlord-digest-cron: "0 0 0 * * 1"
