spring:
  application:
    name: blps1

  datasource:
    url: jdbc:postgresql://localhost:5432/sanctions_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: lians2228@gmail.com
    password: mrxadrcwtyxqabbu
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true